version: 2.1

parameters:
  specgen-version:
    type: string
    default: 2.0.248

  specgen-version-major:
    type: string
    default: v2

jobs:
  build-test:
    working_directory: ~/test-models-go
    docker:
      - image: cimg/go:1.16.4
    steps:
      - checkout
      - run:
          name: Test Go models
          command: |
            cd ./go
            go install github.com/specgen-io/specgen/<<pipeline.parameters.specgen-version-major>>@v<< pipeline.parameters.specgen-version >>
            go generate
            mkdir -p ./test-results
            go install github.com/jstemmer/go-junit-report@v0.9.1
            go test ./... -v 2>&1 | go-junit-report > ./test-results/go-test-report.xml
      - store_test_results:
          path: ./go/test-results

workflows:
  build-test:
    jobs:
      - build-test:
          context: specgen
